default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: cloudtown_test
  username: root
  password: <%= ENV['MYSQL_PASSWORD']%>

test:
  <<: *default
  database: cloudtown_test
  username: root
  password: <%= ENV['MYSQL_PASSWORD']%>

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['MYSQL_DATABASE']%>
  pool: 20
  username: <%= ENV['MYSQL_USERNAME']%>
  password: <%= ENV['MYSQL_PASSWORD']%>
  host: <%= ENV['MYSQL_ADDRESS']%>
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['MYSQL_DATABASE']%>
  pool: 20
  username: <%= ENV['MYSQL_USERNAME']%>
  password: <%= ENV['MYSQL_PASSWORD']%>
  host: <%= ENV['MYSQL_ADDRESS']%>
  port: 3306

